[package]
name = "bitvis-next"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audioviz = "0.6.0"
bdf = "0.6.0"
bit-vec = "0.8.0"
jack = "0.13.0"
mpris = "2.0.1"
